name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '17', '21', '22' ]

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy,rustfmt

      - uses: actions/checkout@v4

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: sudo apt-get update

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Clippy
        run: cargo clippy

      - name: Fmt
        run: cargo fmt --check

      - name: Build native lib
        run: cargo build

      - name: Test
        run: |
          chmod +x gradlew
          ./gradlew -i test jacocoTestReport
